services:
  api:
    ports: !override
      - "18000:8000"
  web:
    build:
      context: ../..
      dockerfile: .github/deploy/Dockerfile.web
    ports:
      - "5173:80"
    depends_on:
      - api
