FROM node:24-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY apps/web ./apps/web
COPY apps/desktop ./apps/desktop
RUN npm run build:web

FROM nginx:1.27-alpine
COPY apps/web/nginx-local.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html
